language: csharp
solution: "./Micro-Services/CsEventService/CsEventService.sln"
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121
addons:
  sonarqube: true
env:
  global:
- secure: $SONAR_TOKEN
script:
  - ./build.sh --quiet verify
