language: java
jdk:
  - oraclejdk8
script:  
- cd BackendMicroService
- mvn test 
- cd ../Mobile-Ionic 
- npm install
- npm install cordova ionic
- cordova platform add android
- ionic build android 
