language: java
jdk:
  - oraclejdk8
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: cd BackendMicroService && mvn test && cd .. && cd Mobile-Ionic && npm install && npm test
