language: java
sudo: required
jdk:
 - oraclejdk8
node_js:
 - "7.5"
before_install:  
- npm install -g npm@2.14.5
- npm install -g cordova ionic
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
script:  
- cd BackendMicroService
- mvn test 
- cd ../Mobile-Ionic 
- npm install
- cordova platform add android
- ionic build android 
