language: csharp
solution: "./Micro-Services/CsEventService/CsEventService.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./Micro-Services/CsEventService/CsEventService.sln