language: java
sudo: required
jdk:
 - oraclejdk8
node_js:
 - "7.5"
before_install:  
- npm install -g npm@2.14.5
- npm install -g cordova ionic
before_script:
  - wget https://dl.google.com/android/repository/tools_r25.1.7-linux.zip
  - unzip tools_r25.1.7-linux.zip
  - echo y | ./tools_r25.1.7-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./tools_r25.1.7-linux/tools/android update sdk --no-ui --all --filter build-tools-25.1.7
  - echo y | ./tools_r25.1.7-linux/tools/android update sdk --no-ui --all --filter android-25
  - echo y | ./tools_r25.1.7-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./tools_r25.1.7-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./tools_r25.1.7-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - ls -l
  - export ANDROID_HOME=$PWD
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/25.1.7
  - mkdir "$ANDROID_HOME/licenses"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
script:  
- cd BackendMicroService
- mvn test 
- cd ../Mobile-Ionic 
- npm install
- npm test
- cordova platform add android
- ionic build android 
