language: java
sudo: required
jdk:
  - oraclejdk8
before_install:  
- npm install -g cordova ionic
script:  
- cd BackendMicroService
- mvn test 
- cd ../Mobile-Ionic 
- npm install
- cordova platform add android
- ionic build android 
