language: java
sudo: required
dist: trusty
services:
- docker
jdk:
- oraclejdk8
node_js:
- '7.5'
addons:
  sonarqube:
    token: $SONAR_TOKEN
before_install:
- npm install -g npm@2.14.5
- npm install -g cordova ionic
before_script:
- wget https://dl.google.com/android/repository/tools_r25.1.7-linux.zip
- unzip tools_r25.1.7-linux.zip
- echo y | ./tools/android update sdk --no-ui --all --filter platform-tools
- echo y | ./tools/android update sdk --no-ui --all --filter build-tools-25.0.1
- echo y | ./tools/android update sdk --no-ui --all --filter android-25
- echo y | ./tools/android update sdk --no-ui --all --filter extra-android-support
- echo y | ./tools/android update sdk --no-ui --all --filter extra-android-m2repository
- echo y | ./tools/android update sdk --no-ui --all --filter extra-google-m2repository
- ls -l
- export ANDROID_HOME=$PWD
- export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/25.0.1
- mkdir "$ANDROID_HOME/licenses"
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
script:
- cd BackendMicroService
- mvn install:install-file -Dfile=lib/sqljdbc42.jar -DgroupId=com.microsoft.sqlserver -DartifactId=sqljdbc42 -Dversion=4.2 -Dpackaging=jar
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- cd com.SII.RegisterService
- docker build -t eureka .
- cd ../com.SII.PersonneService
- docker build -t person .
- cd ../com.SII.EventService
- docker build -t event .
- cd ../com.SII.ClientService
- docker build -t client .
- cd ..
- docker-compose up -d eureka person event client
- cd ../Mobile-Ionic
- npm install
- npm test
- chmod +x hooks/after_prepare/010_add_platform_class.js
- cordova platform add android
- ionic build android
- cd ..
after_success:
- sh set_tags.sh
deploy:
  provider: releases
  api_key:
    secure: mHNRd/t0w+6qXPu0lOLm1TeKzDRUVZqIQrhiWNGfQM74Wv2mdSwT7Pjqi53VryQzpF70YXmcJiVt+ADFVRAMGZ2ANrzOFX2SWcY6xhNu1MZzquMKffwHWQKv15pmu/cvDwKhHkSoLikmAGht3MfGFJUDc8dpOjqshKFaGYMQPKnWwbJW+N+xNsKnCV1cYuH2lcJ0IDjUNqrPYEENwdPlSaX6mHdUT5JJ75cfRrYlqzW3new77fP4vUSffc45uJw98xVusVKb4cq9Iop3/QkddtvgrUQIybMzcvtq8MovRTGMSs9CZFri7TCMO9lRW8tXrbMSX9j5FwaQTn2jCHyzCxwqMx2ivZZMmhLSCj3qx8TAxRVdihhDLV+AAts3fh8HlR8RjVdOpXzm/Nf0O378C7uMwr8FROKV33OBBPFqhy1nqzIJVxiyrwu+GjxctwGYmhcvj6ZB6+mXdTkDXrVOnmw8XYEc4xcp2Sk/9s25x/bl6/OFdxjhdKVWSOZQBqXoHvf/WaHIEPjLNvCUsF/yOS09IoNVeVDcCKgI1MiYl0eVO0pIhnz7E5RFVVLzKPzj/yCtH7hlNvQ0Q4EDO61YlPFySbrRGi3Bnc2He+6n42pAu/QGj8CxfIoPzu1ooqCq6vkAVSgp3L/cr+/fog0K5NMI4oD1kZk2XTi2ZSFwJg0=
  file: "/home/travis/build/TraineeSIIp/PepSIIrup-2017/Mobile-Ionic/platforms/android/build/outputs/apk/android-debug.apk"
  file_glob: "true"
  skip_cleanup: true
  on:
    repo: TraineeSIIp/PepSIIrup-2017
    
    
