language: csharp
solution: "./Micro-Services/CsEventService/CsEventService.sln"
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121
install:
  - nuget restore Micro-Services/CsEventService/CsEventService.sln
script:
  - ./build.sh --quiet verify
