language: java
sudo: required
dist: trusty
install: true
services:
- docker
jdk:
- oraclejdk8
addons:
  sonarqube:
    token: $SONAR_TOKEN
script:
- mvn install:install-file -Dfile=lib/sqljdbc42.jar -DgroupId=com.microsoft.sqlserver -DartifactId=sqljdbc42 -Dversion=4.2 -Dpackaging=jar
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
