language: java
sudo: required
services:
 - docker
jdk:
 - oraclejdk8
node_js:
 - "7.5"
before_install:  
- npm install -g npm@2.14.5
- npm install -g cordova ionic
before_script:
  - wget https://dl.google.com/android/repository/tools_r25.1.7-linux.zip
  - unzip tools_r25.1.7-linux.zip
  - echo y | ./tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./tools/android update sdk --no-ui --all --filter build-tools-25.0.1
  - echo y | ./tools/android update sdk --no-ui --all --filter android-25
  - echo y | ./tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - ls -l
  - export ANDROID_HOME=$PWD
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/25.0.1
  - mkdir "$ANDROID_HOME/licenses"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
script:  
- cd BackendMicroService
- mvn -q install 
- cd com.SII.RegisterService
- docker build -t eureka .
- cd ../com.SII.PersonneService
- docker build -t person .
- cd ../com.SII.EventService
- docker build -t event .
- cd ../com.SII.ClientService
- docker build -t client .
- cd ..
- cd ../Mobile-Ionic 
- npm install
- npm test
- chmod +x hooks/after_prepare/010_add_platform_class.js
- cordova platform add android
- ionic build android 
- cd ..

deploy:
  provider: releases
    api_key:
    secure: "jAy5+lpFyNTKnChWE9tUOykhQ1P2wwM6eRjdMlaJIOkV9dgUAKPuhWIxE5COK+ZDaAzOUQem+J664FHOE4OWT7CDnQMNa0BXJdSpKCW2Xe2UtVY2DhwcuDO9e+t5wrUPHRi/tUjEReJeyT8gKxTwuuT1JYZAUHt6m8iOkp5hnX9ujCHcSknaFEG7cGFPCvaW56Z3P2Vwc1ww72dab5kHYs6FpRnaRVbzW2gM2m2+2tXRVDmOQ8u+FsLsPOaiIgPEqBH6uuNUfhVjKuR3O6Er4fRlPNwrfd8BzU5BmzG0simdkSMYH8+mfanpL+Js/DxUZF4UYSOYgnfcy8SbIG+ZewEZXUay9NFJ7UIkTXn2ZlR3JZe2gAuAsGE8dPj5plc5mm9mwGJgnsIA+hnylpFEdcS4zUNXmngf83Lx8DOgTY7VmOooueijPpKld9za2eaEUJtvUqRIs6WauswguCjJ+I1E6yBzBuLGYIPcqxGweOWIdYo84Yzm6Fk2Z4ulKVNcM8j8j2YdxED2qHStoAdLWltRGdkc+TKBUz9cwVIobDKbXnU+TucmOIp4YfJxJBu+9HpQKvKu8HzXKGltsibhuXBOFjAhcUHz0nbexgENntH1Yi7vwMsZ4Jn+rNOkyXOuv4ISiOC6bxAlZK8x7rqA+RHRIw39quHY1me9Otvp/n0="
  file: "/home/travis/build/TraineeSIIp/PepSIIrup-2017/Mobile-Ionic/platforms/android/build/outputs/apk/android-debug.apk"
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: TraineeSIIp/PepSIIrup-2017

after_success:
- sh set_tags.sh
    
