# Spring properties
spring:
  application:
    name: web-service  # Identify this application

eureka:
  instance:
     prefer-ip-address: true
     ip-address: nantes-0150.sii.fr
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://nantes-0150.sii.fr:1111/eureka/

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port
